app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from app.models.users import Users
from app import db

bp = Blueprint('auth', __name__)

@bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        nameUser = request.form['nameUser']
        passwordUser = request.form['passwordUser']

        user = Users.query.filter_by(nameUser=nameUser, passwordUser=passwordUser).first()

        if user:
            login_user(user)
            flash("¡Inicio de sesión exitoso!", "success")
            if user.rolUser == 'administrador':
                return redirect(url_for('productos.index'))
            else:
                return redirect(url_for('productos.index'))

        
        flash('Credenciales no válidas. Por favor, inténtelo de nuevo.', 'danger')
    
    if current_user.is_authenticated:
        return redirect(url_for('auth.dashboard'))
    return render_template("login/login.html")

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Se ha cerrado la sesión.', 'info')
    return redirect(url_for('auth.login'))

@bp.route('/dashboard')
@login_required
def dashboard():
    if current_user.rolUser == 'administrador':
        data_user = Users.query.all()
        return render_template('login/index.html',data_user=data_user)
    else:
        return redirect(url_for('productos.index'))
    
@bp.route('/auth/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nameUser = request.form['nameUser']
        passwordUser = request.form['passwordUser']

        # Verificar si ya existe algún usuario registrado
        first_user = Users.query.first()
        
        # Si no existe, asignamos el rol de 'administrador'
        if not first_user:
            new_User = Users(nameUser=nameUser, passwordUser=passwordUser, rolUser='administrador')
        else:
            new_User = Users(nameUser=nameUser, passwordUser=passwordUser)
        
        db.session.add(new_User)
        db.session.commit()
        
        return redirect(url_for('auth.login'))

    return render_template('login/add.html')

@bp.route('/auth/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    user = Users.query.get_or_404(id)

    if request.method == 'POST':
        user.nameUser = request.form['nameUser']
        user.passwordUser = request.form['passwordUser']

        if current_user.idUser == 1:
            user.rolUser = request.form['rolUser']

        db.session.commit()
        return redirect(url_for('auth.dashboard'))

    return render_template('login/edit.html', user=user, current_user=current_user)

@bp.route('/auth/delete/<int:id>')
def delete(id):
    User = Users.query.get_or_404(id)
    
    db.session.delete(User)
    db.session.commit()

    return redirect(url_for('auth.dashboard'))

app/templates/login/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Agregar Usuario</title>
</head>
<body>
    <h1>Agregar Usuario</h1>
    <form action="{{ url_for('auth.add') }}" method="post">

        <label for="nameUser">Nombre del Usuario:</label>
        <input type="text" id="nameUser" name="nameUser" required>

        <label for="passwordUser">Contraseña:</label>
        <input type="password" id="passwordUser" name="passwordUser" required>

        <button type="submit">Agregar Usuario</button>
        <a href="{{ url_for('auth.login') }}" id="enlace">Regresar</a>
    </form>
</body>
</html>

app/templates/login/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Editar Usuario</title>
</head>
<body>
    <h1>Editar Usuario</h1>
    <form action="{{ url_for('auth.edit', id=user.idUser) }}" method="post">
        <label for="nameUser">Nombre:</label>
        <input type="text" id="nameUser" name="nameUser" value="{{ user.nameUser }}" required>

        <label for="passwordUser">Contraseña:</label>
        <input type="password" id="passwordUser" name="passwordUser" value="{{ user.passwordUser }}" required>

        {% if current_user.idUser == 1 %}
        <label for="rolUser">Rol:</label>
        <select name="rolUser" id="rolUser">
            <option value="cliente" {% if user.rolUser == 'cliente' %} selected {% endif %}>Cliente</option>
            <option value="administrador" {% if user.rolUser == 'administrador' %} selected {% endif %}>Administrador</option>
        </select>
        {% endif %}

        <button type="submit">Actualizar Usuario</button>
        <a href="{{ url_for('auth.dashboard') }}" id="enlace">Regresar</a>
    </form>
</body>
</html>

app/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Usuarios</title>
</head>
<body>
    <h1>Lista de Usuarios</h1>
    <table>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Paswword</th>
            <th>Acciones</th>
        </tr>
        {% for user in data_user %}
            <tr>
                <td>{{ user.idUser }}</td>
                <td>{{ user.nameUser }}</td>
                <td>{{ user.passwordUser }}</td>
                <td>
                    <a href="{{ url_for('auth.edit', id=user.idUser) }}">Editar</a>
                    {% if user.idUser != 1: %}
                        <a href="{{ url_for('auth.delete', id=user.idUser) }}">Eliminar</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('auth.add') }}">Agregar Usuario</a>
    <br>
    <a href="{{ url_for('productos.index') }}">Ir a lista de productos</a>

</body>
</html>

app/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='icons/icon.css') }}">
</head>
<body>

<div class="container mt-5">
    <div class="col-md-6 offset-md-3">
        <h2>Login</h2>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}             
                    {% for category, message in messages %}
                        <div class="flash-message alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
            {% endif %}
        {% endwith %}

        <form method="post" action="{{ url_for('auth.login') }}">
            <div class="form-group">
                <label for="nameUser">Username</label>
                <input type="text" name="nameUser" id="nameUser" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="passwordUser">Password</label>
                <input type="password" name="passwordUser" id="passwordUser" class="form-control" required>
            </div>

            <button type="submit" class="btn btn-primary">Login</button>
            <a href="auth/add" class="add-user-link">
              <i class="material-icons" style="font-size:36px">person_add</i>
            </a>


        </form>
    </div>
</div>

</body>
</html>